### ISSUE TITLE
Nezobrazí videa v archíve

### ISSUE THREAD

**Issue by Bodinko** [kodi-czsk/plugin.video.rtvs.sk#18]
***Plugin version - 1.8.5
*** Operating System LibreELEC 9.2.1
*** KODI 18.6 Git:newclock5_18.6-Leia

Zdravím pred pár dňami po nejakých updateoch prestal funogovať RTVS.SK plugin. 
Konkrétne v archíve niesu žiadné videa. Live strem funguje.

Viete mi s tým prosim pomocť?

ďakujem.

**Comment by rywko** [comment]
Oprava dostupna v #19

**Comment by Bodinko** [comment]
oprava vyskusana a funguje. 
Dakujem.
V ktorom repozitary by sa mal objavit update na novu verziu?

**Comment by rywko** [comment]
Aktualne ani jeden repozitar negeneruje aktualizaciu doplnku. kodi-czsk prestal fungovat, co po slede udalosti sposobilo vznik noveho repa cder.sk. Doslo k odchodu uzivatelov z repa xbmc-kodi-cz, ktore pre stratu zaujmu tiez prestalo fungovat. Repo cder.sk z neznamych dovodov tiez nespristupnuje novu verziu doplnku

**Comment by lzoubek** [comment]
Prestal fungovat deploy srcipt a proto se nepublikuji nove verze, za chvilku ho opravim

**Comment by lzoubek** [comment]
Uz to zase beha

**Comment by Bodinko** [comment]
Znova sa objavila rovnaka chyba. 
***Plugin version - 1.8.6
*** Operating System LibreELEC 9.2.1
*** KODI 18.6 Git:newclock5_18.6-Leia

**Comment by ghost** [comment]
Oprava dostupna v #20

**Comment by Bodinko** [comment]
vyskusana a funguje. Dakujem
