### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by jesusko** [kodi-czsk/plugin.video.rtvs.sk#2]
Hello guys, 

recently this addon has stopped working. Would it be possible for you to fix it? I enjoyed it pretty much.

Thanks.

**Comment by mx3L** [comment]
Hello, for me it's working. Can you provide log?

**Comment by jesusko** [comment]
Never mind, I thought it was some global issue for everyone. Feel kind of stupid now, tried to re-install addon again and it worked like a charm. 

Thanks for support!

FYI this was error message:
17:57:19 T:2964   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named util
                                            Traceback (most recent call last):
                                              File "C:\Users\JESUS\AppData\Roaming\kodi\addons\plugin.video.rtvs.sk\default.py", line 26, in <module>
                                                import rtvs
                                              File "C:\Users\JESUS\AppData\Roaming\kodi\addons\plugin.video.rtvs.sk\resources\lib\rtvs.py", line 35, in <module>
                                                import util
                                            ImportError: No module named util
                                            -->End of Python script error report<--
